// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pifqddvdfrsqmlbvhqlr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBpZnFkZHZkZnJzcW1sYnZocWxyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMDk1MjUsImV4cCI6MjA3Mzc4NTUyNX0.0p4nINCGE1YnT5E0inWhz_JmkstOBvfVTEyIz2AP0sI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});